name: Resolve Issue with OpenHands

# Trigger this workflow on specific events
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

# Give the workflow necessary permissions
permissions:
  contents: write
  pull-requests: write
  issues: write

# Define the job that will call the reusable workflow
jobs:
  call-openhands-resolver:
    # Specify the runner to use. This must be at the top level of the job.
    runs-on: [self-hosted, <your-runner-label>] # IMPORTANT: Replace with your actual runner label.

    # This is the correct way to call the reusable workflow.
    # It must be a direct child of the job name.
    uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main

    # The 'with' block passes inputs to the reusable workflow.
    # It must also be at the top level of the job.
    with:
      macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
      max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || 50) }}
      base_container_image: ${{ vars.OPENHANDS_BASE_CONTAINER_IMAGE || '' }}
      LLM_MODEL: ${{ vars.LLM_MODEL || 'anthropic/claude-sonnet-4-20250514' }}
      target_branch: ${{ vars.TARGET_BRANCH || 'main' }}
      runner: ${{ vars.TARGET_RUNNER }}

    # The 'secrets' block passes secrets to the reusable workflow.
    # It must also be at the top level of the job.
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
